name: glowing_wave_button
description: A beautiful animated button widget with glowing wave effects and floating words for Flutter applications. Perfect for meditation, relaxation, and interactive UI elements.
version: 1.0.1
homepage: https://github.com/Haraprosad/glowing_wave_button
repository: https://github.com/Haraprosad/glowing_wave_button
issue_tracker: https://github.com/Haraprosad/glowing_wave_button/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # No specific assets needed
